name: ArtifactBox
version: ${project.version}
main: cgc.artifactbox.ArtifactBox
depend: [ BrAPI, PlayerPoints ]

commands:
    sxpage:
        aliases: [ ab ]
        usage: |
            §6/<command> open [装备页名] >> 查看玩家装备页
            §6/<command> reload >> 重载插件